routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){

    Route::resource('users', 'UsersController');
    Route::get('users/{id}/destroy', [
        'uses'  => 'UsersController@destroy',
        'as'    => 'admin.users.destroy'
    ]);

    Route::resource('categories', 'CategoriesController');
    Route::get('categories/{id}/destroy', [
        'uses' => 'CategoriesController@destroy',
        'as' => 'admin.categories.destroy'
    ]);

    Route::resource('tags', 'TagsController');
    Route::get('tags/{id}/destroy', [
        'uses' => 'TagsController@destroy',
        'as' => 'admin.tags.destroy'
    ]);

    Route::resource('articles', 'ArticleController');

    Route::resource('donation', 'DonationController');

    Route::resource('donationcategories', 'DonationCategoryController');

    Route::resource('donor', 'DonorController');

    Route::resource('control', 'ControlController');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('/');

// Route::get('admin/auth/login', [
//     'uses'  => 'HomeController@getLogin',
//     'as'    => 'admin.auth.login'
// ]);

// Route::post('admin/auth/login', [
//     'uses'  => 'HomeController@postLogin',
//     'as'    => 'admin.auth.login'
// ]);

// Route::get('admin/auth/logout', [
//     'uses'  => 'HomeController@getLogout',
//     'as'    => 'admin.auth.logout'
// ]);

app/Control.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Control extends Model
{
    protected $table = 'controls';

    protected $fillable = ['user_master_id', 'donation_id', 'article_id', 'estado', 'fecha_salida'];

    public function article() 
    {
        return $this->belongsTo('App\Article');
    }

    public function donation()
    {
        return $this->belongsTo('App\Donation');
    }

    public function scopeSearch($query, $name)
    {
        return $query->where('name', 'LIKE', "%$name%");
    }
}

app/Http/Controllers/ControlController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Input;

use App\Tag;
use App\Control;
use App\Donation;
use App\Article;
use App\Article_Tag;

use DB;

use Carbon\Carbon;
use Response;
use Illuminate\Support\Collection;

class ControlController extends Controller
{
    public function __construct()
    {
    		
	}
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request){
            $query=trim($request->get('searchText'));
            $pedidos=DB::table('articles as a')->join('article_tag as rt', 'a.id', '=', 'rt.article_id')->join('tags as t', 't.id', '=', 'rt.tag_id')->join('users as u', 'u.id', '=', 'a.user_id')
            ->select('u.name', 'rt.tag_id', 't.name')
            ->where('rt.article_id', 'LIKE', '%'.$query.'%')->get();

            $donations=DB::table('donations as d')->select('name')->get();

            $tags=DB::table('tags as t')->select('t.name')->get();

            return view('admin.control.index', ["pedidos"=>$pedidos, "searchText"=>$query, "donations"=>$donations,"tags"=>$tags,]);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $donations = Donation::orderBy('name', 'asc')->pluck('name', 'id');
        $tags = Tag::orderBy('name', 'asc')->pluck('name', 'id');
        return view('admin.control.create', 
        compact('donations', 'tags'));


        // dd($donation);
        // $pedidos = ArticleTag::orderBy('tag_id', 'asc')->pluck('tag_id', 'name');
        // dd($pedidos);
        //dd($article);

        // $pedidos=DB::table('articles as a')->join('article_tag as rt', 'a.id', '=', 'rt.article_id')->join('tags as t', 't.id', '=', 'rt.tag_id')
        // ->select('rt.tag_id', 't.name')->where('a.id', '=', 2)->get();
        // //dd($pedidos);
        // return view('admin.control.create', 
        // compact('pedidos'));
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // $donations = Donation::orderBy('name', 'asc')->pluck('name', 'id');
        // $tags = Tag::orderBy('name', 'asc')->pluck('name', 'id');
        // if($request){
        // $query=trim($request->get('id'));
        // $dona=trim($request->get('dona'));
        // $need=trim($request->get('need'));
        // $pedidos=DB::table('articles as a')->join('article_tag as rt', 'a.id', '=', 'rt.article_id')->join('tags as t', 't.id', '=', 'rt.tag_id')->join('users as u', 'u.id', '=', 'a.user_id')->join('controls as c', 'a.id', '=', 'c.article_id')->join('donations as d', 'd.id', '=', 'c.donation_id')
        // ->select('u.name', 'rt.tag_id', 't.name')
        // ->where('rt.article_id', '=', '%'.$query.'%', $dona, '=', $need)->get();

        $control = new Control($request->all());
        

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/control/create.blade.php
@extends('layouts.app')

@section('title', 'Add Control')

@section('content')

{{-- {!! Form::open(['route' => 'control.index',
'method' => 'GET',
'class' => 'navbar-form pull-right']) !!}

<div class="input-group mb-3">
{!! Form::text('name', null, [
    'class' => 'form-control' , 
    'placeholder' => 'Buscar Pedidos',
    'aria-describedby' => "search"]) !!}
<span class="input-group-text poin" id="search">Buscar</span>
</div>

{!! Form::close() !!} --}}


  {!! Form::open(['route' => 'control.store', 
                      'method' => 'POST']) !!}

    <div class="form-group">
      {!! Form::label('donations', 'Donativos') !!}
      {!! Form::select('donations[]', $donations, 'dona', ['class' => 'form-control', 'value' => 'dona',
      'multiple', 'required']) !!}
    </div> 

    <div class="form-group">
      {!! Form::label('tags', 'Donativos') !!}
      {!! Form::select('tags[]', $tags, 'need', ['class' => 'form-control', 'value' => 'need', 'multiple', 'required']) !!}
    </div> 

    <div class="form-group">
      {!! Form::label('article_id', 'ID') !!}
      {!! Form::number('article_id', 'id', ['class' => 'form-control', 'value' => 'id', 'required']) !!}
    </div> 
    
     <div class="form-group">
      {!! Form::submit('Agregar', ['class' => 'btn btn-primary']) !!}
    </div>
  {!! Form::close() !!}
@endsection

resources/views/admin/control/index.blade.php
@extends('layouts.app')

@section('title', 'Listar')

@section('content')

<a href="{{ route('control.create') }}" class="btn btn-primary left">New control</a>

  {!! Form::open(['route' => 'control.index',
  'method' => 'GET', 'role'=>'search',
  'class' => 'navbar-form pull-right']) !!}

  <div class="input-group">
    <input type="text" class="form-control" name="searchText" placeholder="Buscar..." value="{{ $searchText }}">
    <span class="input-group-btn">
      <button type="submit" class="btn btn-primary">Buscar</button>
    </span>
  </div>

  {!! Form::close() !!}

  <table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>ID Tag</th>
            <th>Necesidad</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($pedidos as $pedido)
            <tr>
                <td>{{ $pedido->name }}</td>
                <td>{{ $pedido->tag_id }}</td>
                <td>{{ $pedido->name }}</td>
                
                {{-- <td>
                    <a href="{{ route('tags.edit', $tag->id), $tag->id }}" class="btn btn-info">Editar</a>
                    <a href="{{ route('admin.tags.destroy', $tag->id) }}" class="btn btn-danger">Eliminar</a>
                </td> --}}
            </tr>
        @endforeach
    </tbody>
  </table>

@endsection