routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){

    Route::resource('users', 'UsersController');
    Route::get('users/{id}/destroy', [
        'uses'  => 'UsersController@destroy',
        'as'    => 'admin.users.destroy'
    ]);

    Route::resource('categories', 'CategoriesController');
    Route::get('categories/{id}/destroy', [
        'uses' => 'CategoriesController@destroy',
        'as' => 'admin.categories.destroy'
    ]);

    Route::resource('tags', 'TagsController');
    Route::get('tags/{id}/destroy', [
        'uses' => 'TagsController@destroy',
        'as' => 'admin.tags.destroy'
    ]);

    Route::resource('articles', 'ArticleController');

    Route::resource('donation', 'DonationController');

    Route::resource('donationcategories', 'DonationCategoryController');

    Route::resource('donor', 'DonorController');

    Route::resource('control', 'ControlController');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('/');

// Route::get('admin/auth/login', [
//     'uses'  => 'HomeController@getLogin',
//     'as'    => 'admin.auth.login'
// ]);

// Route::post('admin/auth/login', [
//     'uses'  => 'HomeController@postLogin',
//     'as'    => 'admin.auth.login'
// ]);

// Route::get('admin/auth/logout', [
//     'uses'  => 'HomeController@getLogout',
//     'as'    => 'admin.auth.logout'
// ]);

resources/views/admin/partials/errors.blade.php
@if (count($errors) > 0)
<div class="alert alert-danger" role="alert">
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

resources/views/admin/partials/nav.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{ route('control.index') }}">Control <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{ route('users.index') }}">Usuarios</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link disabled" href="{{ route('categories.index') }}">Ciudad</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link disabled" href="{{ route('articles.index') }}">Pedidos</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link disabled" href="{{ route('donation.create') }}">Donativo</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link disabled" href="{{ route('tags.index') }}">Necesidad</a>
        </li>
        <li class="nav-item dropdown navbar-right active">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Opciones
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>

      </ul>
      {{--  <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>  --}}
    </div>
  </nav>